---

- name: Install xorg-server and nvidia drivers.
  pacman:
    pkg: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xorg-server-utils
    - xorg-apps
    - xorg-xinit
    - xf86-video-nouveau
  become: true

- name: Configure xinitrc.
  copy:
    src: xinitrc
    dest: "{{ user_home }}/.xinitrc"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Configure zsh_profile.
  copy:
    src: zprofile
    dest: "{{ user_home }}/.zprofile"
    owner: "{{ user }}"
    group: "{{ user }}"
    
- name: Install freetype2-infinality.
  include: aur/pkg.yml pkg_name=freetype2-infinality

- name: Install fontconfig-infinality.
  include: aur/pkg.yml pkg_name=fontconfig-infinality
