---

#- name: Install emacs.
#  command: pacaur --noconfirm --noedit --needed -S emacs-git

# - name: Make git directory.
#   file:
#     path: /var/git
#     state: directory

# - name: Clone Emacs git repository.
#   git:
#     repo: git://git.sv.gnu.org/emacs.git
#     depth: 1
#     dest: /var/git/

# - name: Clone Emacs configuration.
#   git: repo=ssh://{{ backup_server }}:{{backup_git_home }}/{{ emacs_repo }} dest={{ user_git_home }}/

# - name: Create symlink to Emacs git repository under {{ user_home }}
#   file: src={{ user_git_home }}/{{ emacs_repo }}/ dest={{ user_home }}/.emacs state=link owner={{ user_name }} group={{ user_group }} mode=600

# - name: Install emacs-git.
#   include: aur/pkg.yml pkg_name=emacs-git

- name: Install emacs.
  pacman:
    pkg: emacs
    state: present
  become: true

- name: Create emacs config.
  template:
    src: emacs.ini.j2
    dest: "/home/{{ user }}/.emacs"
