---

- name: Install packages for media.
  pacman:
    pkg: "{{ item }}"
    state: present
  with_items:
    - mpv
    - beet
    - youtube-dl
    - youtube-viewer
  become: true

- name: Configure beets.
  template:
    src: beet_config.yaml.j2
    dest: "/home/{{ user }}/.config/beets/config.yaml"

- name: Make media directory.
  file:
    path: "/home/{{ user }}/media"
    state: directory

    
- name: Install youtube2mp3 script.
