---

- name: Install docker.
  pacman:
    name: docker-git
    state: present

- name: Enable docker.
  service:
    name: docker
    enabled: yes
  
- name: Start docker service.
  service:
    name: docker
    state: started

- name: Add user to docker group.
  user:
    name: "{{ user }}"
    group: docker
    append: yes
